from setuptools import setup

setup(
    name='github-org-mgr',
    version='1.0.0',
    packages=['tests', 'venvNew.lib.python2.7.distutils', 'venvNew.lib.python2.7.encodings',
              'venvNew.lib.python2.7.site-packages.pip', 'venvNew.lib.python2.7.site-packages.pip._vendor',
              'venvNew.lib.python2.7.site-packages.pip._vendor.idna',
              'venvNew.lib.python2.7.site-packages.pip._vendor.pytoml',
              'venvNew.lib.python2.7.site-packages.pip._vendor.certifi',
              'venvNew.lib.python2.7.site-packages.pip._vendor.chardet',
              'venvNew.lib.python2.7.site-packages.pip._vendor.chardet.cli',
              'venvNew.lib.python2.7.site-packages.pip._vendor.distlib',
              'venvNew.lib.python2.7.site-packages.pip._vendor.distlib._backport',
              'venvNew.lib.python2.7.site-packages.pip._vendor.msgpack',
              'venvNew.lib.python2.7.site-packages.pip._vendor.urllib3',
              'venvNew.lib.python2.7.site-packages.pip._vendor.urllib3.util',
              'venvNew.lib.python2.7.site-packages.pip._vendor.urllib3.contrib',
              'venvNew.lib.python2.7.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venvNew.lib.python2.7.site-packages.pip._vendor.urllib3.packages',
              'venvNew.lib.python2.7.site-packages.pip._vendor.urllib3.packages.backports',
              'venvNew.lib.python2.7.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venvNew.lib.python2.7.site-packages.pip._vendor.colorama',
              'venvNew.lib.python2.7.site-packages.pip._vendor.html5lib',
              'venvNew.lib.python2.7.site-packages.pip._vendor.html5lib._trie',
              'venvNew.lib.python2.7.site-packages.pip._vendor.html5lib.filters',
              'venvNew.lib.python2.7.site-packages.pip._vendor.html5lib.treewalkers',
              'venvNew.lib.python2.7.site-packages.pip._vendor.html5lib.treeadapters',
              'venvNew.lib.python2.7.site-packages.pip._vendor.html5lib.treebuilders',
              'venvNew.lib.python2.7.site-packages.pip._vendor.lockfile',
              'venvNew.lib.python2.7.site-packages.pip._vendor.progress',
              'venvNew.lib.python2.7.site-packages.pip._vendor.requests',
              'venvNew.lib.python2.7.site-packages.pip._vendor.packaging',
              'venvNew.lib.python2.7.site-packages.pip._vendor.cachecontrol',
              'venvNew.lib.python2.7.site-packages.pip._vendor.cachecontrol.caches',
              'venvNew.lib.python2.7.site-packages.pip._vendor.webencodings',
              'venvNew.lib.python2.7.site-packages.pip._vendor.pkg_resources',
              'venvNew.lib.python2.7.site-packages.pip._internal',
              'venvNew.lib.python2.7.site-packages.pip._internal.req',
              'venvNew.lib.python2.7.site-packages.pip._internal.vcs',
              'venvNew.lib.python2.7.site-packages.pip._internal.utils',
              'venvNew.lib.python2.7.site-packages.pip._internal.models',
              'venvNew.lib.python2.7.site-packages.pip._internal.commands',
              'venvNew.lib.python2.7.site-packages.pip._internal.operations',
              'venvNew.lib.python2.7.site-packages.idna', 'venvNew.lib.python2.7.site-packages.nose',
              'venvNew.lib.python2.7.site-packages.nose.ext', 'venvNew.lib.python2.7.site-packages.nose.tools',
              'venvNew.lib.python2.7.site-packages.nose.sphinx', 'venvNew.lib.python2.7.site-packages.nose.plugins',
              'venvNew.lib.python2.7.site-packages.wheel', 'venvNew.lib.python2.7.site-packages.wheel.tool',
              'venvNew.lib.python2.7.site-packages.wheel.signatures', 'venvNew.lib.python2.7.site-packages.tinydb',
              'venvNew.lib.python2.7.site-packages.certifi', 'venvNew.lib.python2.7.site-packages.chardet',
              'venvNew.lib.python2.7.site-packages.chardet.cli', 'venvNew.lib.python2.7.site-packages.urllib3',
              'venvNew.lib.python2.7.site-packages.urllib3.util', 'venvNew.lib.python2.7.site-packages.urllib3.contrib',
              'venvNew.lib.python2.7.site-packages.urllib3.contrib._securetransport',
              'venvNew.lib.python2.7.site-packages.urllib3.packages',
              'venvNew.lib.python2.7.site-packages.urllib3.packages.backports',
              'venvNew.lib.python2.7.site-packages.urllib3.packages.ssl_match_hostname',
              'venvNew.lib.python2.7.site-packages.requests', 'venvNew.lib.python2.7.site-packages.setuptools',
              'venvNew.lib.python2.7.site-packages.setuptools.extern',
              'venvNew.lib.python2.7.site-packages.setuptools._vendor',
              'venvNew.lib.python2.7.site-packages.setuptools._vendor.packaging',
              'venvNew.lib.python2.7.site-packages.setuptools.command',
              'venvNew.lib.python2.7.site-packages.pkg_resources',
              'venvNew.lib.python2.7.site-packages.pkg_resources.extern',
              'venvNew.lib.python2.7.site-packages.pkg_resources._vendor',
              'venvNew.lib.python2.7.site-packages.pkg_resources._vendor.packaging'],
    url='https://github.com/jpyoung/github-org-mgr',
    license='MIT',
    author='John Young',
    author_email='jpyoung17@gmail.com',
    description='A tool to manage GitHub Organizations using Github\'s powerful API'
)
